<?php
    $currentTodoDisplay='';
    $completedTodoDisplay='';
foreach ($todos as $todo) {
    if ($todo['deletedFlag'] != 1 && $todo['completedFlag'] !=1) {
        if ($todo['urgentFlag'] == 1) {
            $currentTodoDisplay .='<div class="todoContainer"><div class="urgent">';
        } else {
            $currentTodoDisplay .='<div class="todoContainer"><div>';
        }
        $currentTodoDisplay .= $todo['taskName'] . '<div class="deleteButton" data-id="' . $todo['id'] . '">X</div></div></div>';


    }
    if ($todo['deletedFlag'] != 1 && $todo['completedFlag'] !=0) {
        $completedTodoDisplay .= '<div class="todoContainer"><div>' . $todo['taskName'] . '<div class="deleteButton" data-id="' . $todo['id'] . '">X</div></div><div>';
    }

}
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Todos - See All Todos</title>
    <link rel="stylesheet" type="text/css" href="./css/style.css" />
    <script defer src="./js/script.js"></script>
</head>
<body>
<h1>Todos</h1>
<form method="post" action="/add">
    <label>Task:</label><input type="text" name="taskName" />
    <label>Urgent</label><input type="checkbox" name="urgentFlag" />
    <label>Completed</label><input type="checkbox" name="completedFlag" />
    <input type="submit" value="Add" />
</form>
<section>
    <h2>Still todo:</h2>
    <?php echo $currentTodoDisplay; ?>
</section>
<section>
    <h2>Already done:</h2>
    <?php echo $completedTodoDisplay; ?>
</section>
</body>

</html>