<?php
    $currentTodoDisplay='';
    $completedTodoDisplay='';
foreach ($todos as $todo) {
    if ($todo['deletedFlag'] != 1 && $todo['completedFlag'] !=1) {
        if ($todo['urgentFlag'] == 1) {
            $currentTodoDisplay .='<div class="todoContainer"><div class="urgent">';
        } else {
            $currentTodoDisplay .='<div class="todoContainer"><div>';
        }
        $currentTodoDisplay .= $todo['taskName'] . '<div class="delete button" data-id="' . $todo['id'] . '">X</div><div class="complete button" data-id="' . $todo['id'] . '">&#10003;</div><div class="edit button" data-id="' . $todo['id'] . '">Edit</div></div></div>';


    }
    if ($todo['deletedFlag'] != 1 && $todo['completedFlag'] !=0) {
        $completedTodoDisplay .= '<div class="todoContainer"><div>' . $todo['taskName'] . '<div class="delete button" data-id="' . $todo['id'] . '">X</div><div class="edit button" data-id="' . $todo['id'] . '">Edit</div></div></div>';
    }

}
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <title>Todos - See All Todos</title>
    <link rel="stylesheet" type="text/css" href="./css/style.css" />
    <script defer src="./js/functions.js"></script>
    <script defer src="./js/script.js"></script>
</head>
<body>
<h1>Todos</h1>
<form method="post" action="/add">
    <label>Task:</label><input type="text" name="taskName" />
    <label>Urgent</label><input type="checkbox" name="urgentFlag" />
    <label>Completed</label><input type="checkbox" name="completedFlag" />
    <input type="submit" value="Add" />
</form>
<section>
    <h2>Still todo:</h2>
    <?php echo $currentTodoDisplay; ?>
</section>
<section>
    <h2>Already done:</h2>
    <?php echo $completedTodoDisplay; ?>
</section>

<form id="editForm">
    <h2>Edit Task</h2>
    <label>Task:</label><input type="text" id="taskName" name="taskName" />
    <label>Urgent</label><input type="checkbox" id="urgentFlag" name="urgentFlag" />
    <label>Completed</label><input type="checkbox" id="completedFlag" name="completedFlag" />
    <div class="button closeEditForm" id="closeEditFormButton">X</div>
    <div class="button submitEdit" id="editFormButton">Submit</div>
</form>
</body>

</html>